version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: server
    container_name: server
    command: [ "/app/docker-entrypoint.sh" ]
    ports:
      - 50051:50051
    environment: 
      - TEST=true
